// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi0x9Okkltvroflltec0qJ1KY0v0ep68g',
    appId: '1:85037185556:web:6436096b75b254a5774501',
    messagingSenderId: '85037185556',
    projectId: 'ict602-assignment-2128e',
    authDomain: 'ict602-assignment-2128e.firebaseapp.com',
    storageBucket: 'ict602-assignment-2128e.firebasestorage.app',
    measurementId: 'G-QQSR8RE0G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA73owefYuIQwPo_4gKVFAdWU5noWTMmME',
    appId: '1:85037185556:android:404fee1a3afe30da774501',
    messagingSenderId: '85037185556',
    projectId: 'ict602-assignment-2128e',
    storageBucket: 'ict602-assignment-2128e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU3NZcewmzLvGSoxTxkYKCFTgtQqN7OhU',
    appId: '1:85037185556:ios:904bc8f8ad363599774501',
    messagingSenderId: '85037185556',
    projectId: 'ict602-assignment-2128e',
    storageBucket: 'ict602-assignment-2128e.firebasestorage.app',
    iosBundleId: 'com.example.ict602Assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU3NZcewmzLvGSoxTxkYKCFTgtQqN7OhU',
    appId: '1:85037185556:ios:904bc8f8ad363599774501',
    messagingSenderId: '85037185556',
    projectId: 'ict602-assignment-2128e',
    storageBucket: 'ict602-assignment-2128e.firebasestorage.app',
    iosBundleId: 'com.example.ict602Assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi0x9Okkltvroflltec0qJ1KY0v0ep68g',
    appId: '1:85037185556:web:8275ab2a4eaa8caa774501',
    messagingSenderId: '85037185556',
    projectId: 'ict602-assignment-2128e',
    authDomain: 'ict602-assignment-2128e.firebaseapp.com',
    storageBucket: 'ict602-assignment-2128e.firebasestorage.app',
    measurementId: 'G-36GCF7MHMV',
  );
}
