// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBOWGWqH2tUQ2sfRLB3IERmh1cvF7lOUA',
    appId: '1:396429679826:web:621052a9033e127f83a10b',
    messagingSenderId: '396429679826',
    projectId: 'ict602-assignment-335e6',
    authDomain: 'ict602-assignment-335e6.firebaseapp.com',
    storageBucket: 'ict602-assignment-335e6.firebasestorage.app',
    measurementId: 'G-15WWFSH5PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qcaT4O9Q0pchOU403IfX1ydh_4m3Duc',
    appId: '1:396429679826:android:81144f7ace76d8d383a10b',
    messagingSenderId: '396429679826',
    projectId: 'ict602-assignment-335e6',
    storageBucket: 'ict602-assignment-335e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlnB3pRE1Z0QERH7icHtxHkYQ7QFCrW-Y',
    appId: '1:396429679826:ios:69ca21c18933385483a10b',
    messagingSenderId: '396429679826',
    projectId: 'ict602-assignment-335e6',
    storageBucket: 'ict602-assignment-335e6.firebasestorage.app',
    iosBundleId: 'com.example.ict602Assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlnB3pRE1Z0QERH7icHtxHkYQ7QFCrW-Y',
    appId: '1:396429679826:ios:69ca21c18933385483a10b',
    messagingSenderId: '396429679826',
    projectId: 'ict602-assignment-335e6',
    storageBucket: 'ict602-assignment-335e6.firebasestorage.app',
    iosBundleId: 'com.example.ict602Assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBOWGWqH2tUQ2sfRLB3IERmh1cvF7lOUA',
    appId: '1:396429679826:web:07d44325678222b383a10b',
    messagingSenderId: '396429679826',
    projectId: 'ict602-assignment-335e6',
    authDomain: 'ict602-assignment-335e6.firebaseapp.com',
    storageBucket: 'ict602-assignment-335e6.firebasestorage.app',
    measurementId: 'G-L0ST627RR5',
  );
}
