// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyltEDSYhwE2LMiFHfTWdvJbk1sGx7LXw',
    appId: '1:635573794916:web:7628fc837301a2382b4771',
    messagingSenderId: '635573794916',
    projectId: 'assignment2023141697-8525e',
    authDomain: 'assignment2023141697-8525e.firebaseapp.com',
    storageBucket: 'assignment2023141697-8525e.firebasestorage.app',
    measurementId: 'G-5E65ZV093Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvT_mCrCaSLLzed9ZcnbO2E6SaXSLCKs0',
    appId: '1:635573794916:android:241388b3c1808af32b4771',
    messagingSenderId: '635573794916',
    projectId: 'assignment2023141697-8525e',
    storageBucket: 'assignment2023141697-8525e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnzKWSrdjxDHpHvNqo2u_cPBGZUUg7jKk',
    appId: '1:635573794916:ios:1f5f5a968944f7522b4771',
    messagingSenderId: '635573794916',
    projectId: 'assignment2023141697-8525e',
    storageBucket: 'assignment2023141697-8525e.firebasestorage.app',
    iosClientId: '635573794916-1jrffe36n619t7vakt3b9o34pj9docir.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment2023141697',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnzKWSrdjxDHpHvNqo2u_cPBGZUUg7jKk',
    appId: '1:635573794916:ios:1f5f5a968944f7522b4771',
    messagingSenderId: '635573794916',
    projectId: 'assignment2023141697-8525e',
    storageBucket: 'assignment2023141697-8525e.firebasestorage.app',
    iosClientId: '635573794916-1jrffe36n619t7vakt3b9o34pj9docir.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment2023141697',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyltEDSYhwE2LMiFHfTWdvJbk1sGx7LXw',
    appId: '1:635573794916:web:4d3b9c143d0553e32b4771',
    messagingSenderId: '635573794916',
    projectId: 'assignment2023141697-8525e',
    authDomain: 'assignment2023141697-8525e.firebaseapp.com',
    storageBucket: 'assignment2023141697-8525e.firebasestorage.app',
    measurementId: 'G-J5MKYEWSJ2',
  );

}