// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_PySkhhpKcIZLaCEe5RxDeouq8-cbkfI',
    appId: '1:318318679810:web:a5940e4b7b3aad1f34941b',
    messagingSenderId: '318318679810',
    projectId: 'assignment-2023131125-dc906',
    authDomain: 'assignment-2023131125-dc906.firebaseapp.com',
    storageBucket: 'assignment-2023131125-dc906.firebasestorage.app',
    measurementId: 'G-DXT3KTVCRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9vGPuiSpLPjj0s4gFDO5xTGUG2sng3XI',
    appId: '1:318318679810:android:4dfea523eed811ad34941b',
    messagingSenderId: '318318679810',
    projectId: 'assignment-2023131125-dc906',
    storageBucket: 'assignment-2023131125-dc906.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEbyVQwgLHOc2J6D4K_PmJb7gv0tJlPSU',
    appId: '1:318318679810:ios:ce1f47a747f5f2cd34941b',
    messagingSenderId: '318318679810',
    projectId: 'assignment-2023131125-dc906',
    storageBucket: 'assignment-2023131125-dc906.firebasestorage.app',
    iosClientId: '318318679810-r3sn0uu6udt5jp4gddc2v5p3bbtvbkk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment2023131125',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEbyVQwgLHOc2J6D4K_PmJb7gv0tJlPSU',
    appId: '1:318318679810:ios:ce1f47a747f5f2cd34941b',
    messagingSenderId: '318318679810',
    projectId: 'assignment-2023131125-dc906',
    storageBucket: 'assignment-2023131125-dc906.firebasestorage.app',
    iosClientId: '318318679810-r3sn0uu6udt5jp4gddc2v5p3bbtvbkk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment2023131125',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_PySkhhpKcIZLaCEe5RxDeouq8-cbkfI',
    appId: '1:318318679810:web:1777b9a57d8bb90d34941b',
    messagingSenderId: '318318679810',
    projectId: 'assignment-2023131125-dc906',
    authDomain: 'assignment-2023131125-dc906.firebaseapp.com',
    storageBucket: 'assignment-2023131125-dc906.firebasestorage.app',
    measurementId: 'G-ZP54D9EGDL',
  );

}