// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1L1UTUcFGMxpWZ4gqYeH3ZezVlhMJvKQ',
    appId: '1:31680937048:web:b2782478a5f0af4e109e2d',
    messagingSenderId: '31680937048',
    projectId: 'ict602-app-cf16c',
    authDomain: 'ict602-app-cf16c.firebaseapp.com',
    storageBucket: 'ict602-app-cf16c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO15ItP33ktHtXQFxofTKWP2qQ-tdyDyc',
    appId: '1:31680937048:android:fc9fdb399bf97754109e2d',
    messagingSenderId: '31680937048',
    projectId: 'ict602-app-cf16c',
    storageBucket: 'ict602-app-cf16c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzt1XCoSnEentU3xzh4dADroS0XedzWg',
    appId: '1:31680937048:ios:60090ecc450d05db109e2d',
    messagingSenderId: '31680937048',
    projectId: 'ict602-app-cf16c',
    storageBucket: 'ict602-app-cf16c.firebasestorage.app',
    iosBundleId: 'com.example.ict602App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEzt1XCoSnEentU3xzh4dADroS0XedzWg',
    appId: '1:31680937048:ios:60090ecc450d05db109e2d',
    messagingSenderId: '31680937048',
    projectId: 'ict602-app-cf16c',
    storageBucket: 'ict602-app-cf16c.firebasestorage.app',
    iosBundleId: 'com.example.ict602App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1L1UTUcFGMxpWZ4gqYeH3ZezVlhMJvKQ',
    appId: '1:31680937048:web:8d4c535fb2b13583109e2d',
    messagingSenderId: '31680937048',
    projectId: 'ict602-app-cf16c',
    authDomain: 'ict602-app-cf16c.firebaseapp.com',
    storageBucket: 'ict602-app-cf16c.firebasestorage.app',
  );
}
