// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Yi3d2NYE1FxzestxcoERj0QobzXPUCw',
    appId: '1:357091805206:web:5624f3cb6af0e69c3c0d37',
    messagingSenderId: '357091805206',
    projectId: 'ict602saimen',
    authDomain: 'ict602saimen.firebaseapp.com',
    storageBucket: 'ict602saimen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh453gw9GDrA2Ey6qjQitsQsxEilZCL-g',
    appId: '1:357091805206:android:b8552fd8faa7e6463c0d37',
    messagingSenderId: '357091805206',
    projectId: 'ict602saimen',
    storageBucket: 'ict602saimen.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Yi3d2NYE1FxzestxcoERj0QobzXPUCw',
    appId: '1:357091805206:web:3d1600c0fd1786fa3c0d37',
    messagingSenderId: '357091805206',
    projectId: 'ict602saimen',
    authDomain: 'ict602saimen.firebaseapp.com',
    storageBucket: 'ict602saimen.firebasestorage.app',
  );
}
