// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgjeo0M2wXSIlvDkdspZ3O4-SZFUBbDQo',
    appId: '1:311309458772:web:ed407a2055e1667bedfcc1',
    messagingSenderId: '311309458772',
    projectId: 'ict602-indass-firebase',
    authDomain: 'ict602-indass-firebase.firebaseapp.com',
    storageBucket: 'ict602-indass-firebase.firebasestorage.app',
    measurementId: 'G-YF8JH2GP4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxXcT_7pBOaLa_t6FfYHpVAkAWWioe-0o',
    appId: '1:311309458772:android:5a19c26c37da0d88edfcc1',
    messagingSenderId: '311309458772',
    projectId: 'ict602-indass-firebase',
    storageBucket: 'ict602-indass-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-wq4wvmXsJ-TCtKj2c32zm4lQ2ygyelk',
    appId: '1:311309458772:ios:8d21cb7d99425bf8edfcc1',
    messagingSenderId: '311309458772',
    projectId: 'ict602-indass-firebase',
    storageBucket: 'ict602-indass-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ict602Indass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-wq4wvmXsJ-TCtKj2c32zm4lQ2ygyelk',
    appId: '1:311309458772:ios:8d21cb7d99425bf8edfcc1',
    messagingSenderId: '311309458772',
    projectId: 'ict602-indass-firebase',
    storageBucket: 'ict602-indass-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ict602Indass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgjeo0M2wXSIlvDkdspZ3O4-SZFUBbDQo',
    appId: '1:311309458772:web:e0e313892d67d9acedfcc1',
    messagingSenderId: '311309458772',
    projectId: 'ict602-indass-firebase',
    authDomain: 'ict602-indass-firebase.firebaseapp.com',
    storageBucket: 'ict602-indass-firebase.firebasestorage.app',
    measurementId: 'G-G6JZVLC2DQ',
  );
}
